name = "clapculture-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
APPWRITE_ENDPOINT = "https://cloud.appwrite.io/v1"
APPWRITE_PROJECT_ID = "YOUR_PROJECT_ID"
APPWRITE_API_KEY = "YOUR_API_KEY"
APPWRITE_DATABASE_ID = "YOUR_DATABASE_ID"
JWT_SECRET = "YOUR_JWT_SECRET"
FRONTEND_URL = "http://localhost:3000"
